name: ${project.name}
version: ${project.version}
description: 'Tokens for nickname changes using Essentials'
depend: [Essentials]
softdepend: []
authors: [Stealth2800]
website: http://minerave.com
main: com.stealthyone.mcbc.nicktokens.NickTokens
commands:
  nicktokens:
    aliases: [nt]